baseurl: "https://hongyuanjia.me"
languageCode: "en-us"
title: "Hongyuan | 贾洪愿"
theme: "hugo-ivy"
canonifyurls: true
relativeurls: true
googleAnalytics: "UA-141601756-2"
disqusShortname: "hongyuanjia"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
preserveTaxonomyNames: true
footnotereturnlinkcontents: "↩"

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"
    
menu:
  main:
    - name: "About"
      url: "/en/about/"
      weight: 0
    - name: "Blog"
      url: "/en/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "博客"
      url: "/cn/"
      weight: 3
  en:
    - name: "Home"
      url: "/"
      weight: 0
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 3
    - name: "中文"
      url: "/cn/"
      weight: 4
  cn:
    - name: "首页"
      url: "/"
      weight: 0
    - name: "关于"
      url: "/cn/about/"
      weight: 1
    - name: "博客"
      url: "/cn/"
      weight: 2
    - name: "简历"
      url: "/cn/vitae/"
      weight: 3
    - name: "English"
      url: "/en/"
      weight: 4
    
params:
  description: "A Blog of Hongyuan Jia; 贾洪愿的个人网站"
  disqusURL: "https://weibinqu.xyz"
  github: "https://github.com/hongyuanjia"
  email: "qubinhan@gmail.com"
  footer: "&copy; [Hongyuan Jia](https://hongyuanjia.name) 2019 | [Github](https://github.com/hongyuanjia) | [Twitter](https://twitter.com/jiahony)"

  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  social:
    twitter: "jiahony"
    github: "hongyuanjia"

  author:
    en: "Hongyuan Jia"
    cn: "贾洪愿"
    
  lang:
    edit:
      en: "Suggest an edit of this page"
      cn: "编辑本页"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false